name: Trivy Security Scan 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Scan with Trivy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Date and Time
        id: set-datetime
        run: echo "DATETIME=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Create output directory
        run: mkdir -p "GitHub_Actions/Trivy_Automation"

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin v0.57.0

      - name: Download Trivy vulnerability database
        run: trivy image --download-db-only

      - name: Build docker image
        run: docker build -t my-app:latest .

      - name: Run Trivy vulnerability scanner
        run: |
          OUTPUT_FILE="GitHub_Actions/Trivy_Automation/scan-results-${{ env.DATETIME }}.txt"
          mkdir -p "GitHub_Actions/Trivy_Automation"
          trivy image --format table --ignore-unfixed=false --vuln-type os,library --severity HIGH,CRITICAL --exit-code 1 -o "$OUTPUT_FILE" my-app:latest

      - name: Upload Trivy Scan Results (as Artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Trivy Scan Results
          path: "GitHub_Actions/Trivy_Automation/scan-results-${{ env.DATETIME }}.txt"
