name: build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Build an image from Dockerfile
        run:  docker pull nginx:latest                              #docker build -t 'my-app:${{ github.sha }}' .

      - name: Set current datetime as env variable
        run: echo "DATETIME=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
        
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.60.0
        with:
          image-ref: 'nginx:latest'                                 #'my-app:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          output: 'trivy-results-${{ env.DATETIME }}.txt'
          ignore-unfixed: false
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results as artifact
        if: always()  
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-results
          path: 'trivy-results-${{ env.DATETIME }}.txt'
          
   
